scrape_configs:

- job_name: prometheus
  static_configs:
    - targets: ['prometheus:9090']

- job_name: rabbitmq
  static_configs:
    - targets: ['rabbitmq:15692']

- job_name: cadvisor
  static_configs:
    - targets: ['cadvisor:8080']
